language: julia

os:
  - linux

julia:
  - 1.2
  - 1.3
  - nightly

notifications:
  email: false

jobs:
  allow_failures:
    - os: osx
    - os: windows
    - julia: nightly
    - julia: 1.3
  exclude:
    - julia: 1.3
      os: osx
    - julia: 1.3
      os: windows
    - julia: nightly
      os: osx
    - julia: nightly
      os: windows
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
